<?php
namespace WP2\Download\Archi\Admin;

use WP2\Download\Archi\Registry;
use WP2\Download\Archi\Viz\Mermaid\Generator;

defined( 'ABSPATH' ) || exit;

final class Page {

	private const PAGE_SLUG = 'wp2-architecture';

	public function boot(): void {
		if ( ! is_admin() ) {
			return;
		}
		add_action( 'admin_menu', [ $this, 'add_menu_page' ] );
	}

	public function add_menu_page(): void {
		add_submenu_page(
			'wp2-hub', // Parent slug
			__( 'WP2 Architecture', 'wp2' ),
			__( 'Architecture', 'wp2' ),
			'manage_options',
			self::PAGE_SLUG,
			[ $this, 'render' ]
		);
	}

	public function render(): void {
		$components = Registry::instance()->all();
		$opts = [ 
			'compact' => false,
			'notes' => [ 'WP2 Architecture Overview' ],
			'comments' => [ 'Generated by wp2-archi Admin Page' ],
			'class_defs' => [ 
				'Service' => [ 'fill:#add8e6', 'stroke:#000' ],
				'Manager' => [ 'fill:#90ee90', 'stroke:#000' ],
				'Database' => [ 'fill:#ffe4b5', 'stroke:#000' ],
			],
		];
		$mermaid = Generator::from_components( $components, $opts );

		add_action( 'admin_footer', [ $this, 'render_mermaid_script' ] );
		?>
		<div class="wrap">
			<h1>WP2 System Architecture</h1>
			<p>This diagram is a Mermaid classDiagram example for troubleshooting.</p>
			<div class="wp2-archi-graph">

				<pre class="mermaid">
					<?php echo esc_html( $mermaid ); ?>
				</pre>

			</div>
			<hr>
			<h2>Mermaid Definition</h2>
			<textarea style="width:100%;height:320px; font-family: monospace;" readonly><?php echo $mermaid; ?></textarea>
			<button id="copy-mermaid-btn" class="button">Copy to Clipboard</button>

		</div>
		<?php
	}

	public function render_mermaid_script(): void {
		?>
		<script type="module">
			import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11.9.0/dist/mermaid.esm.min.mjs';
			mermaid.initialize({ startOnLoad: true, logLevel: 'debug', });
		</script>
		<style>
			.wp2-archi-graph {
				background: #f6f7f7;
				border: 1px solid #dcdcde;
				padding: 20px;
				margin-bottom: 20px;
			}

			.mermaid svg {
				max-width: 100%;
				height: auto;
			}
		</style>

		<script>
			document.getElementById('copy-mermaid-btn').addEventListener('click', function () {
				const textarea = document.querySelector('textarea[readonly]');
				textarea.select();
				document.execCommand('copy');
				// Optional: provide user feedback
				this.textContent = 'Copied!';
				setTimeout(() => { this.textContent = 'Copy to Clipboard'; }, 2000);
			});
		</script>
		<?php
	}
}
